spring.application.name=notes-service
server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/notes_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:stage-04-student-hub-demo-secret-key-change-later}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:1440}
