spring.application.name=deadlines-service
server.port=${SERVER_PORT:8082}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/deadlines_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET:stage-04-student-hub-demo-secret-key-change-later}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:1440}
app.notes-service.url=${NOTES_SERVICE_URL:http://localhost:8081}
app.http.timeout-millis=${HTTP_TIMEOUT_MILLIS:2000}
